#!/bin/sh

set -eu

output=config/opencv_imgproc_install.gpr
sysname=$(uname -s)

pkg_config=pkg-config

if ! command -v "$pkg_config" >/dev/null 2>&1; then
    echo "error: pkg-config is required to locate OpenCV Imgproc" >&2
    exit 1
fi

package=
for candidate in opencv5 opencv4 opencv
do
    if "$pkg_config" --exists "$candidate"; then
        package=$candidate
        break
    fi
done

# MacPorts installs opencv4 pkg-config metadata under
# <prefix>/lib/opencv4/pkgconfig rather than the normal
# <prefix>/lib/pkgconfig directory. Only search that location when the
# usual lookup failed; pkg-config remains authoritative afterwards.
if [ -z "$package" ]; then
    if [ "$sysname" = "Darwin" ] && command -v port >/dev/null 2>&1; then
        macports_prefix=$(dirname "$(dirname "$(command -v port)")")
        macports_pkgconfig="${macports_prefix}/lib/opencv4/pkgconfig"
        if [ -d "$macports_pkgconfig" ]; then
            PKG_CONFIG_PATH="${macports_pkgconfig}${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"
            export PKG_CONFIG_PATH
            for candidate in opencv5 opencv4 opencv
            do
                if "$pkg_config" --exists "$candidate"; then
                    package=$candidate
                    break
                fi
            done
        fi
    fi
fi

if [ -z "$package" ]; then
    echo "error: pkg-config package was not found (tried opencv5, opencv4, opencv)" >&2
    exit 1
fi

include_dir=$("$pkg_config" --variable=includedir "$package")

if [ -z "$include_dir" ]; then
    include_dir=$("$pkg_config" --variable=includedir_new "$package")
fi

library_dir=$("$pkg_config" --variable=libdir "$package")

if [ -z "$include_dir" ] || [ -z "$library_dir" ]; then
    echo "error: '$package' does not define a usable include directory and libdir" >&2
    exit 1
fi

# macOS OpenCV from Homebrew or MacPorts is built with Apple clang++ and
# libc++. The C++ shim must use that same compiler and runtime. Linux
# OpenCV uses g++ and libstdc++, which remains the default.
cxx_runtime_switch="-lstdc++"
cxx_driver="g++"
shim_build="Static_PIC"
cxx_toolchain="GNU"
cxx_sysroot=""

if [ "$sysname" = "Darwin" ]; then
    shim_build="Relocatable"
    cxx_toolchain="Apple_Clang"
    cxx_runtime_switch="-lc++"
    if ! command -v xcrun >/dev/null 2>&1; then
        echo "error: xcrun is required to locate Apple clang++ and the macOS SDK" >&2
        exit 1
    fi
    cxx_driver=$(xcrun --find clang++)
    if [ -z "$cxx_driver" ]; then
        echo "error: Apple clang++ is required to compile the OpenCV C++ shim on macOS" >&2
        exit 1
    fi
    cxx_sysroot=$(xcrun --sdk macosx --show-sdk-path)
    if [ -z "$cxx_sysroot" ]; then
        echo "error: could not resolve the macOS SDK path via xcrun --sdk macosx --show-sdk-path" >&2
        exit 1
    fi
fi

case "$include_dir$library_dir$cxx_driver$cxx_sysroot" in
    *\"*)
        echo "error: OpenCV paths containing double quotes are unsupported" >&2
        exit 1
        ;;
esac

mkdir -p config

cat >"$output" <<EOF_GPR
--  Generated by scripts/configure_opencv.sh; do not edit.
abstract project OpenCV_Imgproc_Install is
   type Shim_Build_Kind is ("Static_PIC", "Relocatable");
   type Cxx_Toolchain_Kind is ("GNU", "Apple_Clang");
   Shim_Build : Shim_Build_Kind := "${shim_build}";
   Cxx_Toolchain : Cxx_Toolchain_Kind := "${cxx_toolchain}";
   Include_Switch := "-I${include_dir}";
   Library_Search_Switch := "-L${library_dir}";
   OpenCV_Imgproc_Link_Option := "-lopencv_imgproc";
   OpenCV_Core_Link_Option := "-lopencv_core";
   Cxx_Runtime_Switch := "${cxx_runtime_switch}";
   Cxx_Driver := "${cxx_driver}";
   Cxx_Sysroot := "${cxx_sysroot}";
end OpenCV_Imgproc_Install;
EOF_GPR

echo "OpenCV package: $package"
echo "OpenCV include: $include_dir"
echo "OpenCV library: $library_dir"
