#!/bin/sh

set -eu

output=config/opencv_imgproc_install.gpr

pkg_config=pkg-config

if ! command -v "$pkg_config" >/dev/null 2>&1; then
    echo "error: pkg-config is required to locate OpenCV Imgproc" >&2
    exit 1
fi

package=
for candidate in opencv5 opencv4 opencv
do
    if "$pkg_config" --exists "$candidate"; then
        package=$candidate
        break
    fi
done

if [ -z "$package" ]; then
    echo "error: pkg-config package was not found (tried opencv5, opencv4, opencv)" >&2
    exit 1
fi

include_dir=$("$pkg_config" --variable=includedir "$package")
library_dir=$("$pkg_config" --variable=libdir "$package")

if [ -z "$include_dir" ] || [ -z "$library_dir" ]; then
    echo "error: '$package' does not define usable include/lib directories" >&2
    exit 1
fi

mkdir -p config

cat >"$output" <<EOF_GPR
--  Generated by scripts/configure_opencv.sh; do not edit.
abstract project OpenCV_Imgproc_Install is
   Include_Switch := "-I${include_dir}";
   Library_Search_Switch := "-L${library_dir}";
   OpenCV_Imgproc_Link_Option := "-lopencv_imgproc";
   Cxx_Runtime_Switch := "-lstdc++";
   Cxx_Driver := "g++";
end OpenCV_Imgproc_Install;
EOF_GPR

echo "OpenCV package: $package"
echo "OpenCV include: $include_dir"
echo "OpenCV library: $library_dir"
